### ISSUE TITLE
Serialize seems to output "\n" rather than "\r\n"

### ISSUE THREAD

**Issue by paulfurley** [arran4/golang-ical#2] opened 2019-03-19 23:20 UTC
Hello, and thanks for making this awesome library :)

I've been using it to create a calendar, then calling `Serialize()` and saving that to disk.

However, [this validator](https://icalendar.org/validator.html) complains that lines that span multiple lines (eg long URLs) aren't separated with CRLF ("\r\n").

As a test, I ran `unix2dos` on the generated file, and it then validated.

As a workaround, I've got my code running `strings.Replace(cal.Serialize, "\n", "\r\n", -1)` and now it validates.

But it does seem that the folding (or is it unfolding?) aspect of Serialize isn't working quite according to spec.

Thanks again.
Paul

**Comment by arran4** [comment] 2019-03-20 04:02
Hi Paul,

Thanks! 

It seems the root cause of this is my reliance on "fmt" library. It seems that it only ever writes '\n' regardless of operating system:
```
// doPrintln is like doPrint but always adds a space between arguments
// and a newline after the last argument.
func (p *pp) doPrintln(a []interface{}) {
	for argNum, arg := range a {
		if argNum > 0 {
			p.buf.WriteByte(' ')
		}
		p.printArg(arg, 'v')
	}
	p.buf.WriteByte('\n')
}
```

I will amend this by moving to Print instead of Println and adding '\r','\n' which you rightfully point out the spec requires. Would you like to validate the change for me?

I have pushed the new code into a branch and created a pull request:
https://github.com/arran4/golang-ical/pull/3
Please let me know if that resolves the issue.

**Comment by paulfurley** [comment] 2019-03-20 09:30
hey @arran4, thanks for the fast response!

I've tried this update (while reverting my workaround) [on a branch](https://github.com/paulfurley/iff-2019-events-to-ical/compare/try-updated-ical-library) but unfortunately I'm getting the same thing.

I would've dived in myself but I'm finding it hard to grok the changes you made since all the whitespace changes came in at the same time. It might be worth doing a whitespace-only commit followed by the actual code changes.

**Comment by arran4** [comment] 2019-03-21 01:17
@paulfurley No problem.

I found I missed a (4!!) Fprintln(s).. :P

I have also put the white space changes in a separate file.. Sorry about that. It seems it was caused by IntelliJ having the 'Go fmt' option checked on my desktop, while on my laptop I have a global .editorconfig setup.

Please check the PR https://github.com/arran4/golang-ical/pull/5 (new branch.)

**Comment by paulfurley** [comment] 2019-03-21 09:30
I can confirm that #5 fixes this :)

**Closed** 2019-03-21 11:02 UTC
